name = "LogDensityTestSuite"
uuid = "feb245ec-c857-584e-a66a-22324acf10c6"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.5.5"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
MCMCDiagnostics = "6e857e4b-079a-58c4-aeab-bc2670384359"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ArgCheck = "1, 2"
DocStringExtensions = "0.8, 0.9"
LogDensityProblems = "0.9, 0.10, 0.11, 0.12"
MCMCDiagnostics = "0.3, 0.4"
Sobol = "1"
StatsFuns = "0.9, 1"
julia = "1.1"
UnPack = "1"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Distributions", "ForwardDiff", "Test"]
