name = "LogDensityTestSuite"
uuid = "feb245ec-c857-584e-a66a-22324acf10c6"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
LogDensityProblems = "^0.9.0"
julia = "^1"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ForwardDiff", "Statistics", "Test"]
